
### 게시글 삭제 (PATCH)

DELETE http://localhost:8080/board/delete/16
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTM3MjI3OSwiZXhwIjoxNzUxMzczMTc5fQ.b1biwMJgp4tqDKYu9t14iLIw4WuEiSSaDHLMp5jG-7k

### 게시글 삭제 (PATCH) - 잘못된 토큰

DELETE http://localhost:8080/board/delete/13
Content-Type:  application/json
Authorization: Bearer teyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTIwMjk0OSwiZXhwIjoxNzUxMjAzODQ5fQ.qB7ziJ4JyiUaRoolGns6EOP_Z1UI7HIPBtW0CPkCk-8


### 게시글 삭제 (PATCH) - 없는 게시글

DELETE http://localhost:8080/board/delete/111
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTIwMjk0OSwiZXhwIjoxNzUxMjAzODQ5fQ.qB7ziJ4JyiUaRoolGns6EOP_Z1UI7HIPBtW0CPkCk-8

### 게시글 삭제 (PATCH) - 권한 없음

PATCH http://localhost:8080/board/delete/1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTIwMzg2NiwiZXhwIjoxNzUxMjA0NzY2fQ.4-XJmUVvj4Svv4h1dG2CIRhfO8hJxEx2UMhUdkzKreQ
