jwt:
  secret: my-secret-key-for-jwt-signing
  validity-in-ms: 900000
  refresh-validity-in-ms: 604800000

spring:
  application:
    name: board
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
        order_updates: true
  data:
    redis:
      host: localhost
      port: 6379

