### 댓글 생성
POST http://localhost:8080/api/boards/16/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTM2OTA4MCwiZXhwIjoxNzUxMzY5OTgwfQ.29C41CMUqHU5V4oYW3cnUxdLBgaDUiUsxfVzEZV-Cpk

{
  "content": "aaaasdfasdfasdfasdfasd 게시판입니다."
}

### 댓글 수정
PATCH http://localhost:8080/api/boards/16/comments/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTM2MDE1NCwiZXhwIjoxNzUxMzYxMDU0fQ.Hga9shoOdnYC8ucmrJur_x_Sre0UxLSzjkh3JWDf8PM

{
"content": "수정 완료입니다."
}

### 댓글 삭제
DELETE http://localhost:8080/api/boards/6/comments/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlkIjoxLCJpYXQiOjE3NTI4MjcwMjYsImV4cCI6MTc1MjgyNzkyNn0.JO6dfyVtWr4Gu0cJTBHgtwevTOQcXSr3sqDYgpgRsuc

### 대댓글 생성
POST http://localhost:8080/api/boards/4/comments/2/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlkIjoxLCJpYXQiOjE3NTIwNDEzNTYsImV4cCI6MTc1MjA0MjI1Nn0.pWSXGtIHjDb2Dobo4YzAGG3yNgq595EnszUnciAAwYA

{
"content": "aaaaaㅇㄹ다."
}
