### 회원가입 테스트 (POST)
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "userId": "junwook123",
  "password": "1234pass!",
  "username": "준욱",
  "nickname": "주니"
}

### 로그인 테스트 (POST)
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "userId": "gg",
  "password": "gg"
}

### 게시글 생성 (POST)

POST http://localhost:8080/board/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTIwMjk0OSwiZXhwIjoxNzUxMjAzODQ5fQ.qB7ziJ4JyiUaRoolGns6EOP_Z1UI7HIPBtW0CPkCk-8

{
"title": "첫 번째 sdafasdfsadfasdf판",
"content": "이것은 첫 번째 테스트asdfasdfasdfasdfasd 게시판입니다."
}

### 게시글 생성 (POST) - 잘못된 토큰

POST http://localhost:8080/board/new
Content-Type: application/json
Authorization: Bearer tteyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTE3NjE1NSwiZXhwIjoxNzUxMTc3MDU1fQ.kBSFtDaIAxpQlnbiL0o-EpQzj0tOmlpZSed69ZbenD4

{
  "title": "첫 번째 게시판",
  "content": "이것은 첫 번째 테스트 게시판입니다."
}


### 게시글 삭제 (POST)

POST http://localhost:8080/board/delete?id=12
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTIwMjk0OSwiZXhwIjoxNzUxMjAzODQ5fQ.qB7ziJ4JyiUaRoolGns6EOP_Z1UI7HIPBtW0CPkCk-8

### 게시글 삭제 (POST) - 잘못된 토큰

POST http://localhost:8080/board/delete?id=11
Content-Type:  application/json
Authorization: Bearer teyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTIwMjk0OSwiZXhwIjoxNzUxMjAzODQ5fQ.qB7ziJ4JyiUaRoolGns6EOP_Z1UI7HIPBtW0CPkCk-8


### 게시글 삭제 (POST) - 없는 게시글

POST http://localhost:8080/board/delete?id=1111
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTIwMjk0OSwiZXhwIjoxNzUxMjAzODQ5fQ.qB7ziJ4JyiUaRoolGns6EOP_Z1UI7HIPBtW0CPkCk-8

### 게시글 삭제 (POST) - 권한 없음

POST http://localhost:8080/board/delete?id=1
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnZyIsImlhdCI6MTc1MTIwMzg2NiwiZXhwIjoxNzUxMjA0NzY2fQ.4-XJmUVvj4Svv4h1dG2CIRhfO8hJxEx2UMhUdkzKreQ
